# Version, required
version: 0.2.0
# The MIDI channel assigned to the MC6Pro
midi_channel: 3
# The list of MIDI channels, the position in the list determines the channel number (1 based)
midi_channels:
- name: Iridium
- name: Scarlett
- name: MC6Pro
- name: H9
- name: Timeline
- name: Aeros
# Use navigator mode
navigator: One Button
# Color schemas
colors:
- name: default
  bank_color: black
  bank_background_color: lightyellow
  preset_color: black
  preset_background_color: lightyellow
- name: navigator
  bank_color: red
  bank_background_color: yellow
  preset_color: red
  preset_background_color: yellow
- name: bypass
  preset_color: black
  preset_toggle_color: white
  preset_background_color: darkgreen
  preset_toggle_background_color: red
# The list of MIDI messages, order is not important
messages:
- {channel: Iridium, name: Iridium Disable, type: CC, number: 102, value: 0}
- {channel: Iridium, name: Iridium Enable, type: CC, number: 102, value: 127}
- {channel: Iridium, name: Iridium Bank 0, type: CC, number: 0, value: 0}
- {channel: Iridium, name: Iridium Clean, type: PC, number: 0}
- {channel: Iridium, name: Iridium Burry, type: PC, number: 1}
- {channel: Iridium, name: Iridium Distortion, type: PC, number: 2}
- {channel: Iridium, name: Iridium Max Distortion, type: PC, number: 3}
- {channel: H9, name: H9 Disable, type: CC, number: 1, value: 0}
- {channel: H9, name: H9 Enable, type: CC, number: 0, value: 0}
- {channel: H9, name: H9 Chorus SquareModWah, type: PC, number: 0}
- {channel: H9, name: H9 Chorus PhasyChorus, type: PC, number: 1}
- {channel: H9, name: H9 Chorus Polymodelicious, type: PC, number: 2}
- {channel: H9, name: H9 Phaser FunkPhase, type: PC, number: 3}
- {channel: H9, name: H9 Phaser SawModPhaser, type: PC, number: 4}
- {channel: H9, name: H9 Phaser Vibraphaser, type: PC, number: 5}
- {channel: H9, name: H9 Wah BigModdedPlanets, type: PC, number: 6}
- {channel: H9, name: H9 Wah LessEvenAutoWah, type: PC, number: 7}
- {channel: H9, name: H9 Wah PhasyWah, type: PC, number: 8}
- {channel: Timeline, name: Timeline Disable, type: CC, number: 102, value: 0}
- {channel: Timeline, name: Timeline Enable, type: CC, number: 102, value: 127}
- {channel: Timeline, name: Timeline Bank 0, type: CC, number: 0, value: 0}
- {channel: Timeline, name: Timeline Bank 1, type: CC, number: 0, value: 1}
- {channel: Timeline, name: Timeline Easy Delay, type: PC, number: 100}
- {channel: Timeline, name: Timeline Heavy Delay, type: PC, number: 101}
- {channel: Aeros, name: Aeros Main Click, type: CC, number: 45, value: 8}
- {channel: Aeros, name: Aeros Aux Click, type: CC, number: 45, value: 9}
- {channel: Aeros, name: MSB, type: CC, number: 0, value: 0}
- {channel: Aeros, name: FWIW, type: PC, number: 0}
- {channel: Aeros, name: Swirling, type: PC, number: 1}
- {channel: Aeros, name: Saints and Martyrs, type: PC, number: 2}
# startup messages
on_startup: [H9 Enable, Iridium Enable, Timeline Enable]
# Banks - as a list
banks:
- name: Noodling
  description: A selection of cool guitar sounds
  display_description: true
- name: H9 Chorus
  description: H9 chorus sounds
  display_description: true
  presets:
  - short_name: Enabled
    toggle_name: Disabled
    colors: bypass
    toggle_mode: true
    toggle_group: 2
    messages:
    - {midi_message: H9 Disable, toggle: one}
    - {midi_message: H9 Enable, toggle: two}
  - short_name: SquareModWah
    messages:
    - {midi_message: H9 Chorus SquareModWah}
  - short_name: PhasyChorus
    messages:
    - {midi_message: H9 Chorus PhasyChorus}
  - short_name: Polymodelicious
    messages:
    - {midi_message: H9 Chorus Polymodelicious}
- name: H9 Phaser
  description: H9 phaser sounds
  display_description: true
  presets:
  - short_name: Enabled
    toggle_name: Disabled
    colors: bypass
    toggle_mode: true
    toggle_group: 2
    messages:
    - {midi_message: H9 Disable, toggle: one}
    - {midi_message: H9 Enable, toggle: two}
  - short_name: FunkPhase
    messages:
    - {midi_message: H9 Phaser FunkPhase}
  - short_name: SawModPhaser
    messages:
    - {midi_message: H9 Phaser SawModPhaser}
  - short_name: Vibraphaser
    messages:
    - {midi_message: H9 Phaser Vibraphaser}
- name: H9 Wah
  description: H9 wah sounds
  display_description: true
  presets:
  - short_name: Enabled
    toggle_name: Disabled
    colors: bypass
    toggle_mode: true
    toggle_group: 2
    messages:
    - {midi_message: H9 Disable, toggle: one}
    - {midi_message: H9 Enable, toggle: two}
  - short_name: BigModdedPlanets
    messages:
    - {midi_message: H9 Wah BigModdedPlanets}
  - short_name: LessEvenAutoWah
    messages:
    - {midi_message: H9 Wah LessEvenAutoWah}
  - short_name: PhasyWah
    messages:
    - {midi_message: H9 Wah PhasyWah}
- name: Timeline
  description: Various delay sounds
  display_description: true
  presets:
  - short_name: Enabled
    toggle_name: Disabled
    colors: bypass
    toggle_mode: true
    toggle_group: 3
    messages:
    - {midi_message: Timeline Disable, toggle: one}
    - {midi_message: Timeline Enable, toggle: two}
  - short_name: Easy Delay
    messages:
    - {midi_message: Timeline Bank 0}
    - {midi_message: Timeline Easy Delay}
  - short_name: Heavy Delay
    messages:
    - {midi_message: Timeline Bank 0}
    - {midi_message: Timeline Heavy Delay}
- name: Iridium
  description: Iridium choices
  display_description: true
  presets:
  - short_name: Enabled
    toggle_name: Disabled
    colors: bypass
    toggle_mode: true
    toggle_group: 4
    messages:
    - {midi_message: Iridium Disable, toggle: one}
    - {midi_message: Iridium Enable, toggle: two}
  - short_name: Clean
    messages:
    - {midi_message: Iridium Bank 0}
    - {midi_message: Iridium Clean}
  - short_name: Burry
    messages:
    - {midi_message: Iridium Bank 0}
    - {midi_message: Iridium Burry}
  - short_name: Distortion
    messages:
    - {midi_message: Iridium Bank 0}
    - {midi_message: Iridium Distortion}
  - short_name: Max Distortion
    messages:
    - {midi_message: Iridium Bank 0}
    - {midi_message: Iridium Max Distortion}
- name: Aeros Looper
  description: Aeros Looper config
  display_description: true
  presets:
  - short_name: Main Click
    toggle_name: Aux Click
    colors: bypass
    toggle_mode: true
    toggle_group: 4
    messages:
    - {midi_message: Aeros Main Click, toggle: one}
    - {midi_message: Aeros Aux Click, toggle: two}
  - short_name: Adjust Main Click
    messages:
    - {midi_message: Aeros Main Click, toggle: one}
  - short_name: Adjust Toggle Click
    messages:
    - {midi_message: Aeros Aux Click, toggle: two}
- name: For What It's Worth
  description: Crosby, Stills, Nash and Young
  display_description: true
  messages:
    - {midi_message: MSB}
    - {midi_message: FWIW}
- name: Swirling
  description: The Air Swirls
  display_description: true
  messages:
    - {midi_message: MSB}
    - {midi_message: Swirling}
- name: Saints and Martyrs
  description: Thanks to Flannery OConnor
  display_description: true
  messages:
    - {midi_message: MSB}
    - {midi_message: Saints and Martyrs}
- name: Prelude in C# Minor
  description: Rachmaninoff
  display_description: true
